let
    Source = Json.Document(Web.Contents("https://raw.githubusercontent.com/alexanderlewisstevens/course_data/main/data/processed/course_all_processed.json")),
    ToTable = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    Expand = Table.ExpandRecordColumn(
        ToTable,
        "Column1",
        {
            "term",
            "crn",
            "course",
            "section",
            "title",
            "course_type",
            "meeting_dates",
            "time",
            "days",
            "hours",
            "room",
            "instructor",
            "seats",
            "enrolled",
            "time_start_24",
            "time_end_24",
            "time_start_minutes",
            "time_end_minutes",
            "days_canonical",
            "days_list",
            "date_start",
            "date_end",
            "crosslist",
            "crosslisted_crn",
            "crosslisted_enrollment",
            "total_enrollment",
            "total_seats",
            "conflicts",
            "gta_eligible",
            "lower_crosslist"
        },
        {
            "Term",
            "CRN",
            "Course",
            "Sec",
            "Title",
            "Course Type",
            "Meeting Dates",
            "Time",
            "Days",
            "Hrs",
            "Room",
            "Instructor",
            "Seat",
            "Enr",
            "Time Start 24",
            "Time End 24",
            "Time Start Minutes",
            "Time End Minutes",
            "Days Canonical",
            "Days List",
            "Date Start",
            "Date End",
            "Crosslist",
            "Crosslisted CRN",
            "Crosslisted Enr",
            "Total Enr",
            "Total Seat",
            "Conflicts",
            "gta_eligible",
            "Lower Crosslist"
        }
    ),
    Typed = Table.TransformColumnTypes(
        Expand,
        {
            {"Term", type text},
            {"CRN", type text},
            {"Course", type text},
            {"Sec", type text},
            {"Title", type text},
            {"Course Type", type text},
            {"Meeting Dates", type text},
            {"Time", type text},
            {"Days", type text},
            {"Hrs", type text},
            {"Room", type text},
            {"Instructor", type text},
            {"Seat", Int64.Type},
            {"Enr", Int64.Type},
            {"Time Start 24", type text},
            {"Time End 24", type text},
            {"Time Start Minutes", Int64.Type},
            {"Time End Minutes", Int64.Type},
            {"Days Canonical", type text},
            {"Days List", type text},
            {"Date Start", type text},
            {"Date End", type text},
            {"Crosslist", type text},
            {"Crosslisted CRN", type text},
            {"Crosslisted Enr", Int64.Type},
            {"Total Enr", Int64.Type},
            {"Total Seat", Int64.Type},
            {"Conflicts", type text},
            {"gta_eligible", type logical},
            {"Lower Crosslist", type logical}
        }
    ),
    CrosslistedSet = Table.AddColumn(
        Typed,
        "Crosslisted Set",
        each
            let
                parts = List.RemoveItems(
                    Text.Split(Text.Combine(List.RemoveNulls({[CRN], [Crosslist]}), ","), ","),
                    {""}
                )
            in
                Text.Combine(List.Sort(List.Distinct(parts)), ","),
        type text
    ),
    Clean = Table.RemoveColumns(CrosslistedSet, {"Crosslisted CRN"})
in
    Clean
